<?php
/**
 * Product image able to also display product labels / pictos
 *
 * @var $block \Magento\Catalog\Block\Product\Image
 * @var $escaper Magento\Framework\Escaper
 */
?>
<?php $productLabels = $block->getProductLabels(); ?>
<span class="product-image-container"
      style="width:<?= $escaper->escapeHtml($block->getWidth()) ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ $block->getRatio() * 100 ?>%;">
        <?php if ($productLabels): ?>
            <?php foreach ($productLabels as $class => $labels):?>
                <div class="<?= $escaper->escapeHtml($class); ?>">
                    <?php foreach ($labels as $label): ?>
                        <img src="<?= $escaper->escapeUrl($label['image']); ?>"
                             alt="<?= $escaper->escapeHtml($label['alt']) ?? ''; ?>"
                             title="<?= $escaper->escapeHtml($label['alt']) ?? ''; ?>"/>
                    <?php endforeach ;?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <img class="product-image-photo"
            <?= $escaper->escapeHtmlAttr($block->getCustomAttributes()) ?>
            src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
             max-width="<?= $escaper->escapeHtml($block->getWidth()) ?>"
             max-height="<?= $escaper->escapeHtml($block->getHeight()) ?>"
             alt="<?= $escaper->escapeHtml(
                 $block->stripTags($block->getLabel(), null, true)
             ) ?>"/>
    </span>
</span>
