<?php
/**
 * Product label visual template
 *
 * @var $block \Smile\ProductLabel\Block\ProductLabel\ProductLabel
 * @var $escaper Magento\Framework\Escaper
 */
?>
<?php $productLabels = $block->getProductLabels(); ?>

<?php if ($productLabels): ?>
    <?php foreach ($productLabels as $class => $labels):?>
        <div class="<?= $escaper->escapeHtml($class); ?>">
            <?php foreach ($labels as $label): ?>
                <img src="<?= $escaper->escapeUrl($label['image']); ?>"
                     alt="<?= $escaper->escapeHtml($label['alt']) ?? ''; ?>"
                     title="<?= $escaper->escapeHtml($label['alt']) ?? ''; ?>"/>
            <?php endforeach ;?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

